services:
  pg:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dairy
      POSTGRES_USER: dairy
      POSTGRES_DB: dairy
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dairy-net

volumes:
  pg-data:

networks:
  dairy-net:
